language: java

jdk:
  - openjdk8

branches:
  only:
    - master

script:
  - ./gradlew --no-daemon clean build

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew --no-daemon publishPlugins
    on:
      branch: master
