name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Publish plugin
        run: ./gradlew publishPlugins
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          gradlePublishKey: ${{ secrets.gradlePublishKey }}
          gradlePublishSecret: ${{ secrets.gradlePublishSecret }}